[package]
name = "py-kornia"
version = "0.0.9"
edition = "2021"

[lib]
name = "kornia_rs"
crate-type = ["cdylib"]

[dependencies]
kornia_rs = { path = ".." }
dlpack-rs = {version = "^0.1.1"}
pyo3 = { version = "0.20", features = ["extension-module"] }