[package]
name = "std_mean"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true
include.workspace = true
publish = false

[dependencies]
argh = { workspace = true }
indicatif = { version = "0.17", features = ["rayon"] }
kornia = { workspace = true }
rayon = "1"
walkdir = "2"
