[package]
name = "kornia-pnp"
description = "Perspective-n-Point solvers for kornia"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []

[dependencies]
kornia-linalg = { workspace = true }
kornia-lie = { workspace = true }
kornia-imgproc = { workspace = true }
glam = { version = "0.30.0", default-features = false }
thiserror = { workspace = true }

nalgebra = "0.32"

[dev-dependencies]
approx = { workspace = true }
