[package]
name = "kornia-apriltag"
authors = ["Aditya Kumar <git@adityais.dev>", "kornia.org <edgar@kornia.org>"]
description = "AprilTag marker detection and decoding in Rust"

categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = true
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
kornia-image = { workspace = true }
kornia-imgproc = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
kornia-io = { workspace = true }
criterion = { workspace = true }
apriltag = "0.4"
aprilgrid = "0.6"
image = "0.25"

[[bench]]
name = "bench_decoding"
harness = false

[[bench]]
name = "bench_tagfamily"
harness = false
