[package]
name = "kornia-vlm"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Vision Language Models in Rust"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
include = { workspace = true }

[dependencies]
candle-core = { workspace = true }
candle-examples = { workspace = true }
candle-nn = { workspace = true }
candle-transformers = { workspace = true }
circular-buffer = { version = "1.1.0" }
hf-hub = { workspace = true }
kornia-image = { workspace = true }
kornia-imgproc = { workspace = true }
kornia-io = { workspace = true }
kornia-tensor = { workspace = true }
log = { workspace = true }
minijinja = { version = "2.12.0", features = ["loader"] }
num2words = "1.2.0"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokenizers = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
rand = "0.9.0"

[features]
default = []
cuda = ["candle-core/cuda", "candle-nn/cuda", "candle-transformers/cuda"]
flash-attn = ["candle-transformers/flash-attn"]
