[package]
name = "kornia-vlm"
description = "Vision Language Models in Rust"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
log = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
minijinja = { version = "2.12.0", features = ["loader"] }
thiserror = { workspace = true }

kornia-image = { workspace = true }
kornia-tensor = { workspace = true }
kornia-io = { workspace = true }
kornia-imgproc = { workspace = true }

candle-core = { workspace = true }
candle-transformers = { workspace = true }
candle-examples = { workspace = true }
candle-nn = { workspace = true }
hf-hub = { workspace = true }
tokenizers = { workspace = true }

gstreamer = "0.24.2"
gstreamer-app = "0.24.2"
gstreamer-video = "0.24.2"
image = "0.25.6"

num2words = "=1.2.0"

[dev-dependencies]
rand = "0.9.0"
env_logger = { workspace = true }

[features]
cuda = ["candle-core/cuda", "candle-transformers/cuda", "candle-nn/cuda"]
