[package]
name = "kornia-vlm"
description = "Vision Language Models in Rust"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
log = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

kornia-image = { workspace = true }
kornia-tensor = { workspace = true }
kornia-io = { workspace = true }
kornia-imgproc = { workspace = true }

candle-core = { version = "0.9.1", features = ["mkl"] }
candle-transformers = { version = "0.9.1" }
candle-examples = "0.9.1"
candle-nn = { version = "0.9.1" }
hf-hub = "0.4.2"
tokenizers = { version = "0.21.1", features = ["http"] }

[dev-dependencies]
rand = "0.9.0"

# candle-onnx = "0.9.1"
# ort = "1.16"          # or latest version
ndarray = "0.15" # for easy tensor handling

[features]
cuda = ["candle-core/cuda", "candle-transformers/cuda", "candle-nn/cuda"]
debug = []
