[package]
name = "onnx"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
kornia.workspace = true
ort-sys = { version = "2.0.0-rc.8" }
ort = { version = "2.0.0-rc.8", features = [
    "load-dynamic",
    "half",
], default-features = false }
rerun = "0.18"
