[package]
name = "onnx"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
include = { workspace = true }

[dependencies]
argh = { workspace = true }
kornia = { workspace = true }
kornia-tensor = { workspace = true }
ort = { version = "2.0.0-rc.10", default-features = false, features = [
  "half",
  "load-dynamic",
] }
ort-sys = { version = "2.0.0-rc.10" }
rerun = { workspace = true }
