[package]
name = "smol_vlm_convo"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
include = { workspace = true }

[dependencies]
argh = { workspace = true }
color-eyre = "0.6.3"
crossterm = "0.28.1"
kornia-image = { workspace = true }
kornia-io = { workspace = true }
kornia-tensor = { workspace = true }
kornia-vlm = { workspace = true, features = [] }
ratatui = "0.29.0"
reqwest = { version = "0.12.15", features = ["blocking"] }
tempfile = "3.8"
textwrap = "0.16.2"

[features]
cuda = ["kornia-vlm/cuda"]
