[package]
name = "copper"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
include = { workspace = true }

[dependencies]
bincode = { workspace = true }
cu29 = "0.8.0"
cu29-helpers = "0.8.0"
kornia = { workspace = true, features = ["gstreamer"] }
rerun = { workspace = true }
tempfile = "3.19"
