[package]
name = "dora-imgproc"
version = "0.1.0"
edition = "2021"

[dependencies]
dora-node-api = { version = "0.3", features = ["tracing"] }
dora-image-utils = { path = "../image-utils" }
eyre = "0.6"
kornia = { version = "0.1.8"}

arrow = "54.2.1"
arrow-arith = "54.2.1"
chrono = "0.4.39"
