[package]
name = "paligemma"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
publish = false

[dependencies]
argh = { workspace = true }
kornia-io = { workspace = true }
kornia-vlm = { workspace = true }

[features]
cuda = ["kornia-vlm/cuda"]
