[package]
name = "smol_vlm"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
include = { workspace = true }

[dependencies]
argh = { workspace = true }
kornia-image = { workspace = true }
kornia-io = { workspace = true }
kornia-tensor = { workspace = true }
kornia-vlm = { workspace = true }
reqwest = { version = "0.12.15", features = ["blocking"] }

[features]
cuda = ["kornia-vlm/cuda"]
