[package]
name = "smol_vlm2"
version = "0.1.0"
authors = ["Andrew Shen <andrewshen31@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
argh = { workspace = true }
ctrlc = { workspace = true }
env_logger = { workspace = true }
gstreamer = "0.23.5"
gstreamer-app = "0.23.5"
gstreamer-video = "0.23.5"
kornia = { workspace = true, features = ["v4l"] }
kornia-image = { workspace = true }
kornia-io = { workspace = true }
kornia-tensor = { workspace = true }
kornia-vlm = { workspace = true }
log = "0.4"
reqwest = { version = "0.12.15", features = ["blocking"] }
rerun = { workspace = true }
thiserror = { workspace = true }

[features]
cuda = ["kornia-vlm/flash-attn", "kornia/cuda"]
gstreamer = ["kornia-io/gstreamer"]
