[package]
name = "icp_registration"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
include = { workspace = true }

[dependencies]
argh = { workspace = true }
env_logger = { workspace = true }
kornia = { workspace = true }
rerun = { workspace = true }
