[package]
name = "kornia-tensor"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Lightweight tensor library in Rust for computer vision"
homepage.workspace = true
repository.workspace = true
license.workspace = true
publish = true

[dependencies]
bincode = { workspace = true, optional = true }
num-traits = { workspace = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[features]
bincode = ["dep:bincode"]
serde = ["dep:serde"]
