[package]
name = "ros-z-nodes"
version = "0.1.0"
authors = ["Edgar Riba <edgar.riba@gmail.com>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
argh = { workspace = true }
bytes = "1"
ctrlc = { workspace = true }
env_logger = { workspace = true }
flume = "0.12"
foxglove = "0.16.1"
kornia-image = { workspace = true }
kornia-imgproc = { workspace = true }
kornia-io = { workspace = true, features = ["v4l"] }
log = { workspace = true }
nix = { version = "0.30.1", features = ["time"] }
prost = "0.14.1"
prost-types = "0.14.1"
ros-z = { git = "https://github.com/ZettaScaleLabs/ros-z.git", branch = "main", features = [
  "protobuf"
] }
serde = { workspace = true, features = ["derive"] }
tokio = { version = "1", features = ["full"] }
zenoh = { version = "1.7", features = ["shared-memory"] }

[build-dependencies]
prost-build = "0.14.1"
