[package]
name = "ros-z-nodes"
version = "0.1.0"
authors = ["Edgar Riba <edgar.riba@gmail.com>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
argh = { workspace = true }
ctrlc = { workspace = true }
env_logger = { workspace = true }
flume = "0.12"
foxglove = "0.16.1"
kornia-io = { workspace = true, features = ["v4l"] }
kornia-image = { workspace = true }
log = { workspace = true }
nix = { version = "0.30.1", features = ["time"] }
prost = "0.14.1"
prost-types = "0.14.1"
ros-z = { git = "https://github.com/ZettaScaleLabs/ros-z.git", branch = "main", features = ["protobuf"] }
#ros-z = { path = "/home/edgar/software/ros-z/ros-z", features = ["protobuf"] }
serde = { workspace = true, features = ["derive"] }
zenoh = "1.6"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
prost-build = "0.14.1"
