[package]
name = "dora-image-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "54.3.0"
dora-node-api = { version = "0.3", features = ["tracing"] }
eyre = "0.6"
kornia = { version = "0.1.8"}
